platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

project 'ProductsShop', {
    'Debug' => :debug,
    'Release' => :release,
    'E2E-Debug' => :debug,
    'E2E-Release' => :release,
    'Stage-Debug' => :debug,
    'Stage-Release' => :release,
    'Prod-Debug' => :debug,
    'Prod-Release' => :release
}

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ProductsShop' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  use_native_modules!

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
