import LocalizedStrings from 'react-native-localization';

export const strings = new LocalizedStrings({
    'en-GB': {
        currency: '€',
        close: 'Close',
        cancel: 'Cancel',
        accept: 'Accept',
        submit: 'Submit',
        decline: 'Decline',
        dismiss: 'Dismiss',
        remove: 'Remove',
        back: 'Back',
        next: 'Next',
        edit: 'Edit',
        skip: 'Skip',
        continue: 'Continue',
        confirm: 'Confirm',
        change: 'Change',
        optional: 'Optional',
        noInternetTitle: 'No internet connection.',
        loading: 'Loading',
        reloading: 'Reloading',
        appUpdateTitle: 'An app update is available. Please update now.',
        updateNow: 'Update Now',
        updateLater: 'Update Later',
        you: 'You',
        yes: 'Yes',
        no: 'No',
        total: 'Total',
        successModalTitle: 'Success',
        errorModalTitle: 'Something went wrong',
        headerTitle: 'Products Shop',
        addToCart: 'Add to Cart',
        proceedToPurchase: 'Proceed to Purchase',
        productsEmptyPlaceholder: 'No products found',
        clearCart: 'Clear Cart',
        cartEmptyPlaceholder: 'Your cart is empty',
        // Form labels
        forms: {
            username: 'Username',
            password: 'Password',
            firstName: 'First Name',
            lastName: 'Last Name',
            address: 'Address',
            dateOfBirth: 'Date of Birth',
            phoneNumber: 'Phone Number',
            mobileNumber: 'Mobile Number',
            email: 'Email Address',
        },

        // Numbers
        zero: 'zero',
        one: 'one',
        two: 'two',
        three: 'three',
        four: 'four',
        five: 'five',
        six: 'six',
        seven: 'seven',
        eight: 'eight',
        nine: 'nine',
        ten: 'ten',
        eleven: 'eleven',
        twelve: 'twelve',
        thirteen: 'thirteen',
        fourteen: 'fourteen',
        fifteen: 'fifteen',
        sixteen: 'sixteen',
        seventeen: 'seventeen',
        eighteen: 'eighteen',
        nineteen: 'nineteen',
        twenty: 'twenty',
        thirty: 'thirty',
        forty: 'forty',
        fifty: 'fifty',
        sixty: 'sixty',
        seventy: 'seventy',
        eighty: 'eighty',
        ninety: 'ninety',
        hundred: 'hundred',
        thousand: 'thousand',
        million: 'million',
        billion: 'billion',
        trillion: 'trillion',
        quadrillion: 'quadrillion',
        quintillion: 'quintillion',
        sextillion: 'sextillion',
        septillion: 'septillion',
        octillion: 'octillion',
        nonillion: 'nonillion',
    },
});
